[build]
  base    = "app"          # your Next app lives here
  publish = ".next"        # publish path is relative to base
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Optional: nice URL so /app opens the installer page
[[redirects]]
  from = "/app"
  to   = "/app.html"
  status = 200
